HUTECHClassroom.Web/Controllers/HomeController.cs
using HUTECHClassroom.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace HUTECHClassroom.Web.Controllers;
public sealed class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

HUTECHClassroom.Web/Controllers/PostsController.cs
using HUTECHClassroom.Domain.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using X.PagedList;

namespace HUTECHClassroom.Web.Controllers;

[Authorize(DeanOrTrainingOfficePolicy)]
public sealed class PostsController : BaseEntityController<Post>
{
    public IActionResult Index(int? page, int? size)
    {
        int pageIndex = page ?? 1;
        int pageSize = size ?? 5;
        return View(DbContext.Posts
            .Include(p => p.Classroom)
            .Include(p => p.User)
            .OrderByDescending(x => x.CreateDate)
            .ToPagedList(pageIndex, pageSize));
    }

    // GET: Posts/Details/5
    public async Task<IActionResult> Details(Guid? id)
    {
        if (id == null || DbContext.Posts == null)
        {
            return NotFound();
        }

        var post = await DbContext.Posts
            .Include(p => p.Classroom)
            .Include(p => p.User)
            .FirstOrDefaultAsync(m => m.Id == id);
        if (post == null)
        {
            return NotFound();
        }

        return View(post);
    }

    // GET: Posts/Create
    public IActionResult Create()
    {
        ViewData["ClassroomId"] = new SelectList(DbContext.Classrooms, "Id", "Title");
        ViewData["UserId"] = new SelectList(DbContext.Users, "Id", "UserName");
        return View();
    }

    // POST: Posts/Create
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("Content,Link,ClassroomId,UserId,Id,CreateDate")] Post post)
    {
        if (ModelState.IsValid)
        {
            post.Id = Guid.NewGuid();
            DbContext.Add(post);
            await DbContext.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        ViewData["ClassroomId"] = new SelectList(DbContext.Classrooms, "Id", "Title", post.ClassroomId);
        ViewData["UserId"] = new SelectList(DbContext.Users, "Id", "UserName", post.UserId);
        return View(post);
    }

    // GET: Posts/Edit/5
    public async Task<IActionResult> Edit(Guid? id)
    {
        if (id == null || DbContext.Posts == null)
        {
            return NotFound();
        }

        var post = await DbContext.Posts.FindAsync(id);
        if (post == null)
        {
            return NotFound();
        }
        ViewData["ClassroomId"] = new SelectList(DbContext.Classrooms, "Id", "Title", post.ClassroomId);
        ViewData["UserId"] = new SelectList(DbContext.Users, "Id", "UserName", post.UserId);
        return View(post);
    }

    // POST: Posts/Edit/5
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(Guid id, [Bind("Content,Link,ClassroomId,UserId,Id,CreateDate")] Post post)
    {
        if (id != post.Id)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            try
            {
                DbContext.Update(post);
                await DbContext.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!PostExists(post.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }
        ViewData["ClassroomId"] = new SelectList(DbContext.Classrooms, "Id", "Title", post.ClassroomId);
        ViewData["UserId"] = new SelectList(DbContext.Users, "Id", "UserName", post.UserId);
        return View(post);
    }

    // GET: Posts/Delete/5
    public async Task<IActionResult> Delete(Guid? id)
    {
        if (id == null || DbContext.Posts == null)
        {
            return NotFound();
        }

        var post = await DbContext.Posts
            .Include(p => p.Classroom)
            .Include(p => p.User)
            .FirstOrDefaultAsync(m => m.Id == id);
        if (post == null)
        {
            return NotFound();
        }

        return View(post);
    }

    // POST: Posts/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(Guid id)
    {
        if (DbContext.Posts == null)
        {
            return Problem("Entity set 'ApplicationDbContext.Posts'  is null.");
        }
        var post = await DbContext.Posts.FindAsync(id);
        if (post != null)
        {
            DbContext.Posts.Remove(post);
        }

        await DbContext.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }

    private bool PostExists(Guid id)
    {
        return DbContext.Posts.Any(e => e.Id == id);
    }
}

HUTECHClassroom.Web/Controllers/UsersController.cs
using AutoMapper.QueryableExtensions;
using HUTECHClassroom.Domain.Constants;
using HUTECHClassroom.Domain.Entities;
using HUTECHClassroom.Web.ViewModels.ApplicationUsers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Reflection;
using X.PagedList;

namespace HUTECHClassroom.Web.Controllers;

[Authorize(Roles = $"{RoleConstants.Dean},{RoleConstants.TrainingOffice},{RoleConstants.Administrator}")]
public sealed class UsersController : BaseEntityController<ApplicationUser>
{
    public IActionResult Index(int? page, int? size)
    {
        int pageIndex = page ?? 1;
        int pageSize = size ?? 5;
        return View(DbContext.Users
            .Include(a => a.Faculty)
            .Include(a => a.ApplicationUserRoles)
            .ThenInclude(a => a.Role)
            .OrderBy(x => x.UserName)
            .ToPagedList(pageIndex, pageSize));
    }

    public async Task<IActionResult> Details(Guid? id)
    {
        if (id == null || DbContext.Users == null)
        {
            return NotFound();
        }

        var applicationUser = await DbContext.Users
            .Include(a => a.Faculty)
            .Include(a => a.ApplicationUserRoles)
            .ThenInclude(a => a.Role)
            .FirstOrDefaultAsync(m => m.Id == id);
        if (applicationUser is null || applicationUser.UserName is null || applicationUser.Email is null)
        {
            return NotFound();
        }
        var viewModel = new UserViewModel
        {
            Id = applicationUser.Id,
            UserName = applicationUser.UserName,
            Email = applicationUser.Email,
            FirstName = applicationUser.FirstName,
            LastName = applicationUser.LastName,
            FacultyName = applicationUser.Faculty?.Name ?? string.Empty
        };
        return View(viewModel);
    }

    public IActionResult ImportUsers()
    {
        var viewModel = new ImportUsersFromExcelViewModel();
        Type type = typeof(ImportedUserViewModel);
        PropertyInfo[] propertyInfos = type.GetProperties();
        viewModel.PropertyNames = propertyInfos.Select(x => x.Name);
        ViewData["RoleName"] = new SelectList(DbContext.Roles, "Name", "Name");
        return View(viewModel);
    }
    [HttpPost]
    public async Task<IActionResult> ImportUsers(ImportUsersFromExcelViewModel viewModel)
    {
        if (viewModel.File == null || viewModel.File.Length == 0)
        {
            ViewBag.Error = "Please select a file to upload."; Type type = typeof(ImportedUserViewModel);
            PropertyInfo[] propertyInfos = type.GetProperties();
            viewModel.PropertyNames = propertyInfos.Select(x => x.Name);
            ViewData["RoleName"] = new SelectList(DbContext.Roles, "Name", "Name");
            return View(viewModel);
        }

        if (!Path.GetExtension(viewModel.File.FileName).Equals(".xlsx", StringComparison.OrdinalIgnoreCase))
        {
            ViewBag.Error = "Please select an Excel file (.xlsx)."; Type type = typeof(ImportedUserViewModel);
            PropertyInfo[] propertyInfos = type.GetProperties();
            viewModel.PropertyNames = propertyInfos.Select(x => x.Name);
            ViewData["RoleName"] = new SelectList(DbContext.Roles, "Name", "Name");
            return View(viewModel);
        }

        var userViewModels = ExcelService.ReadExcelFileWithColumnNames<ImportedUserViewModel>(viewModel.File.OpenReadStream(), null);

        var existingUsers = await DbContext.Users
            .Include(u => u.ApplicationUserRoles)
            .ThenInclude(ar => ar.Role)
            .Where(u => userViewModels.Select(x => x.UserName).Contains(u.UserName))
            .ToListAsync();

        var newUsers = userViewModels
            .Where(vm => !existingUsers.Select(x => x.UserName).Contains(vm.UserName))
            .AsQueryable()
            .ProjectTo<ApplicationUser>(Mapper.ConfigurationProvider)
            .ToList();

        foreach (var user in existingUsers)
        {
            DbContext.Entry(user).State = EntityState.Modified;
            foreach (var applicationUserRole in user.ApplicationUserRoles)
            {
                if (applicationUserRole.Role is { Name: { } })
                    await UserManager.RemoveFromRoleAsync(user, applicationUserRole.Role.Name).ConfigureAwait(false);
            }
            await UserManager.AddToRoleAsync(user, viewModel.RoleName).ConfigureAwait(false);
        }

        foreach (var user in newUsers)
        {
            if (string.IsNullOrEmpty(user.UserName)) continue;
            var result = await UserManager.CreateAsync(user, user.UserName).ConfigureAwait(false);
            if (result.Succeeded)
            {
                await UserManager.AddToRoleAsync(user, viewModel.RoleName).ConfigureAwait(false);
            }
        }

        ViewBag.Success = $"Successfully imported and updated {userViewModels.Count} users.";
        return RedirectToAction("Index");
    }
    // GET: ApplicationUsers/Create
    public IActionResult Create()
    {
        ViewData["FacultyId"] = new SelectList(DbContext.Faculties, "Id", "Name")
            .Append(new SelectListItem("None", Guid.Empty.ToString()));
        ViewData["RoleName"] = new SelectList(DbContext.Roles, "Name", "Name");
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(CreateUserViewModel viewModel)
    {
        if (ModelState.IsValid && viewModel.RoleName is { })
        {
            var applicationUser = new ApplicationUser
            {
                UserName = viewModel.UserName,
                Email = viewModel.Email,
                FirstName = viewModel.FirstName,
                LastName = viewModel.LastName,
                FacultyId = viewModel.FacultyId != Guid.Empty ? viewModel.FacultyId : null
            };
            await UserManager.CreateAsync(applicationUser, applicationUser.UserName);
            await UserManager.AddToRoleAsync(applicationUser, viewModel.RoleName);
            return RedirectToAction(nameof(Index));
        }
        ViewData["FacultyId"] = new SelectList(DbContext.Faculties, "Id", "Name", viewModel.FacultyId).Append(new SelectListItem("None", Guid.Empty.ToString()));
        ViewData["RoleName"] = new SelectList(DbContext.Roles, "Name", "Name", viewModel.RoleName);
        return View(viewModel);
    }
    [Authorize(Roles = RoleConstants.Administrator)]
    public async Task<IActionResult> Edit(Guid? id)
    {
        if (id == null || DbContext.Users == null)
        {
            return NotFound();
        }

        var applicationUser = await DbContext.Users.FindAsync(id);
        if (applicationUser is null || applicationUser.UserName is null || applicationUser.Email is null)
        {
            return NotFound();
        }
        var viewModel = new EditUserViewModel
        {
            Id = applicationUser.Id,
            UserName = applicationUser.UserName,
            Email = applicationUser.Email,
            FirstName = applicationUser.FirstName,
            LastName = applicationUser.LastName,
            FacultyId = applicationUser.FacultyId ?? Guid.Empty
        };
        ViewData["FacultyId"] = new SelectList(DbContext.Faculties, "Id", "Name", viewModel.FacultyId).Append(new SelectListItem("None", Guid.Empty.ToString()));
        ViewData["RoleName"] = new SelectList(DbContext.Roles, "Name", "Name");
        return View(viewModel);
    }
    [Authorize(Roles = RoleConstants.Administrator)]
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(Guid id, EditUserViewModel viewModel)
    {
        if (id != viewModel.Id)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            var applicationUser = await DbContext.Users
                .Include(u => u.ApplicationUserRoles)
                .ThenInclude(ar => ar.Role)
                .SingleOrDefaultAsync(u => u.Id == viewModel.Id);
            if (applicationUser is null)
            {
                return NotFound();
            }
            applicationUser.Id = viewModel.Id;
            applicationUser.UserName = viewModel.UserName;
            applicationUser.Email = viewModel.Email;
            applicationUser.FirstName = viewModel.FirstName ?? applicationUser.FirstName;
            applicationUser.LastName = viewModel.LastName ?? applicationUser.LastName;
            applicationUser.FacultyId = viewModel.FacultyId != Guid.Empty ? viewModel.FacultyId : null;

            try
            {
                DbContext.Update(applicationUser);
                foreach (var applicationUserRole in applicationUser.ApplicationUserRoles)
                {
                    if (applicationUserRole.Role is { Name: { } })
                        await UserManager.RemoveFromRoleAsync(applicationUser, applicationUserRole.Role.Name);
                }
                await UserManager.AddToRoleAsync(applicationUser, viewModel.RoleName ?? RoleConstants.Student);
                await DbContext.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ApplicationUserExists(applicationUser.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }
        ViewData["FacultyId"] = new SelectList(DbContext.Faculties, "Id", "Name", viewModel.FacultyId).Append(new SelectListItem("None", Guid.Empty.ToString()));
        ViewData["RoleName"] = new SelectList(DbContext.Roles, "Name", "Name", viewModel.RoleName);
        return View(viewModel);
    }
    [Authorize(Roles = RoleConstants.Administrator)]
    public async Task<IActionResult> Delete(Guid? id)
    {

HUTECHClassroom.Web/Views/Home/Index.cshtml
@using HUTECHClassroom.Domain.Constants;
@using HUTECHClassroom.Domain.Entities;
@using HUTECHClassroom.Persistence;
@using Microsoft.AspNetCore.Identity

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@inject ApplicationDbContext dbContext;

@{
    ViewData["Title"] = "Home Page";
    var user = await UserManager.GetUserAsync(User);
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>HUTECH Classroom Admin website.</p>
    @if (SignInManager.IsSignedIn(User) && user is not null && (await UserManager.IsInRoleAsync(user, RoleConstants.Administrator) || await UserManager.IsInRoleAsync(user, RoleConstants.Dean) || await UserManager.IsInRoleAsync(user, RoleConstants.TrainingOffice)))
        {
        <div class="row row-cols-1 row-cols-md-4 g-4" role="group" aria-label="Entities">
            <div class="col">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Answers</h5>
                        <p class="card-text">@dbContext.Answers.Count() rows.</p>
                        <a class="btn btn-dark" asp-area="" asp-controller="Answers" asp-action="Index">Answers</a>
                        <a class="btn btn-success" asp-area="" asp-controller="Answers" asp-action="Create">Create</a>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Classrooms</h5>
                        <p class="card-text">@dbContext.Classrooms.Count() rows.</p>
                        <a class="btn btn-dark" asp-area="" asp-controller="Classrooms" asp-action="Index">Classrooms</a>
                        <a class="btn btn-success" asp-area="" asp-controller="Classrooms" asp-action="Create">Create</a>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Comments</h5>
                        <p class="card-text">@dbContext.Comments.Count() rows.</p>
                        <a class="btn btn-dark" asp-area="" asp-controller="Comments" asp-action="Index">Comments</a>
                        <a class="btn btn-success" asp-area="" asp-controller="Comments" asp-action="Create">Create</a>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Exercises</h5>
                        <p class="card-text">@dbContext.Exercises.Count() rows.</p>
                        <a class="btn btn-dark" asp-area="" asp-controller="Exercises" asp-action="Index">Exercises</a>
                        <a class="btn btn-success" asp-area="" asp-controller="Exercises" asp-action="Create">Create</a>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Faculties</h5>
                        <p class="card-text">@dbContext.Faculties.Count() rows.</p>
                        <a class="btn btn-dark" asp-area="" asp-controller="Faculties" asp-action="Index">Faculties</a>
                        <a class="btn btn-success" asp-area="" asp-controller="Faculties" asp-action="Create">Create</a>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Groups</h5>
                        <p class="card-text">@dbContext.Groups.Count() rows.</p>
                        <a class="btn btn-dark" asp-area="" asp-controller="Groups" asp-action="Index">Groups</a>
                        <a class="btn btn-success" asp-area="" asp-controller="Groups" asp-action="Create">Create</a>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Majors</h5>
                        <p class="card-text">@dbContext.Majors.Count() rows.</p>
                        <a class="btn btn-dark" asp-area="" asp-controller="Majors" asp-action="Index">Majors</a>
                        <a class="btn btn-success" asp-area="" asp-controller="Majors" asp-action="Create">Create</a>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Missions</h5>
                        <p class="card-text">@dbContext.Missions.Count() rows.</p>
                        <a class="btn btn-dark" asp-area="" asp-controller="Missions" asp-action="Index">Missions</a>
                        <a class="btn btn-success" asp-area="" asp-controller="Missions" asp-action="Create">Create</a>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Posts</h5>
                        <p class="card-text">@dbContext.Posts.Count() rows.</p>
                        <a class="btn btn-dark" asp-area="" asp-controller="Posts" asp-action="Index">Posts</a>
                        <a class="btn btn-success" asp-area="" asp-controller="Posts" asp-action="Create">Create</a>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Projects</h5>
                        <p class="card-text">@dbContext.Projects.Count() rows.</p>
                        <a class="btn btn-dark" asp-area="" asp-controller="Projects" asp-action="Index">Projects</a>
                        <a class="btn btn-success" asp-area="" asp-controller="Projects" asp-action="Create">Create</a>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Subjects</h5>
                        <p class="card-text">@dbContext.Subjects.Count() rows.</p>
                        <a class="btn btn-dark" asp-area="" asp-controller="Subjects" asp-action="Index">Subjects</a>
                        <a class="btn btn-success" asp-area="" asp-controller="Subjects" asp-action="Create">Create</a>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Users</h5>
                        <p class="card-text">@dbContext.Users.Count() rows.</p>
                        <a class="btn btn-dark" asp-area="" asp-controller="Users" asp-action="Index">Users</a>
                        <a class="btn btn-success" asp-area="" asp-controller="Users" asp-action="Create">Create</a>
                    </div>
                </div>
            </div>
            </div>
        }
</div>